### ISSUE TITLE
Signal.export does not handle Path object

### ISSUE THREAD

**Issue by gregoiremenguy** [Quefumas/gensound#21]
Hi gensound maintainers,

I just started trying gensound and I observed that `filename` argument of `Signal.export` must be a string. I think that it could be great if we could give it `Path` object too (from `pathlib`).  

One possible solution: 
```
def export(self, filename, sample_rate=44100, **kwargs):
        file = os.fspath(filename)  # add this line to get a string from Path
        audio = self.realise(sample_rate)
        audio.export(file, **kwargs)
```

Maybe it would be more appropiate to add the `file = os.fspath(filename)` somewhere else so that all functions which export sounds can take `Path` object as input (I don't know if this is relevant). 

Best regards

**Comment by Quefumas** [comment]
Hello @gregoiremenguy and welcome,

Thank you for your suggestion, and also for taking the time to examine the code.

Could you elaborate more on what would this feature offer? That is, under what circumstances would users prefer to use `Path` objects rather than string filename? Also, is it common among other libraries to support `Path` objects?

**Comment by gregoiremenguy** [comment]
Hello,

I think this is more and more common to use `Path` object in python. It is really usefull (e.g. we can easily navigate in directories, list all files in a directory) and enables to manipulate an object made to represent paths (not a string which could represent something else). 

In the standard `open(filename, right)` function, they allow filename to be a string or a Path. In the code of `open` they use the `file = os.fspath(filename)` to handle it.

**Comment by Quefumas** [comment]
Hi,

This makes sense. Also, thanks for giving a reference for the use of `os.fspath` for this purpose.

I just pushed a fix for this in `Audio.export` since that is the actual bottleneck for file export, and furthermore in some cases users may conceivably want to use this method directly, rather than calling `Signal.export`.

Feel free to raise any other suggestions or questions you come up with.

**Comment by Quefumas** [comment]
Sorry, didn't actually push, it should be available now.

**Comment by gregoiremenguy** [comment]
Thank you :)
